services:
  # Production service
  nuxt-app:
    build:
      context: .
      target: production
      args:
        - API_BASE_URL=${API_BASE_URL}
        - API_BPH_URL=${API_BPH_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL}
      - API_BPH_URL=${API_BPH_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
