services:
  # Production service
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
        - API_BPH_URL=${API_BPH_URL}
        - API_MASTER_DATA_URL=${API_MASTER_DATA_URL}
        - API_SUPER_APP_URL=${API_SUPER_APP_URL}
        - API_PERSURATAN_URL=${API_PERSURATAN_URL}
        - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
        - KEYCLOAK_REDIRECT_URL=${KEYCLOAK_REDIRECT_URL}
        - KEYCLOAK_LOGOUT_URL=${KEYCLOAK_LOGOUT_URL}
    ports:
      - "3002:3001"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  shared-network:
    external: true
