export const TEXT = {
  title: "Kementerian Haji dan Umrah",
  welcome: "Selamat Datang",
  welcomeDescription: "di Kementerian Haji dan Umrah",
  reminderDescription: "Jangan lupa catat kehadiranmu hari ini.",
  clockIn: "Absen Masuk",
  clockOut: "Absen Keluar",
  lainnya: "Lainnya",
  presensi: "Presensi",
  kepegawaian: "Kepegawaian",
  persuratan: "Persuratan",
  sop: "SOP",
  laporan: "Laporan",
  semuaMenu: "Menu",
  laporanKehadiran: "Laporan Kehadiran",
  jadwalKerja: "Jadwal Kerja",
  stafKhusus: "Staf Khusus",
  stafKhususDescription: "08:00 - 17:00",
  persenPemotongan: "Persentase Pemotongan",
  infoKehadiran: "Klik tombol di atas untuk mencatat kehadiran Anda",
  riwayatKehadiran: "Riwayat Kehadiran",
  lihatSemua: "Lihat Semua",
  belumAdaDataKehadiranHariIni: "Belum ada data kehadiran hari ini",
  apakahAndaYakinInginMelakukanAbsen:
    "Apakah Anda yakin ingin melakukan absen?",
  yaAbsenMasuk: "Ya, Absen Masuk",
  yaAbsenKeluar: "Ya, Absen Keluar",
  batal: "Batal",
  konfirmasiAbsenMasuk: "Konfirmasi Absen Masuk",
  konfirmasiAbsenKeluar: "Konfirmasi Absen Keluar",
  harapIzinkanAksesLokasiUntukMelakukanAbsen:
    "Harap izinkan akses lokasi untuk melakukan absen",
  peringatan: "Peringatan",
  terjadiKesalahan: "Terjadi kesalahan, silahkan coba lagi",
  sukses: "Sukses",
  absenBerhasil: "Absen berhasil",
  absenMasukBerhasil: "Absen masuk berhasil",
  absenKeluarBerhasil: "Absen keluar berhasil",
  loginSSO: "Login SSO",
  keluarDariAkun: "Keluar dari akun",
  ya: "Ya",
  tidak: "Tidak",
  apakahAndaYakinInginKeluarDariAkun:
    "Apakah Anda yakin ingin keluar dari akun?",
  atasanLangsung: "Atasan Langsung",
  divisi: "Divisi",
  infoAkun: "Informasi Akun",
  pengaturan: "Pengaturan",
  infoPersonal: "Info Personal",
  infoKepegawaian: "Info Kepegawaian",
  infoLainnya: "Info Lainnya",
  ubahKataSandi: "Ubah Kata Sandi",
  pengingatPresensi: "Pengingat Presensi",
  bahasa: "Bahasa",
  pemotongan: "Pemotongan",
  memuatData: "Memuat data...",
  cobaLagi: "Coba Lagi",
  tidakAdaDataKehadiranUntukBulanIni:
    "Tidak ada data kehadiran untuk bulan ini",
  listDisposisi: "List Disposisi",
  suratMasuk: "Surat Masuk",
  suratKeluar: "Surat Keluar",
  nomor: "Nomor",
  download: "Download",
  disposisi: "Disposisi",
  lihatDetail: "Detail",
  buatSurat: "Buat Surat",
  type: "Type",
  nomorSurat: "Nomor Surat",
  tanggalSurat: "Tanggal Surat",
  fileSurat: "File Surat",
  fileSuratDescription: "File surat harus berupa dokumen Docx",
  simpan: "Simpan",
  buatDisposisi: "Buat Disposisi",
  belumAdaCatatan:
    "Belum ada catatan. Klik 'Tambah Catatan' untuk menambahkan.",
  tambahCatatan: "Tambah Catatan",
  hapus: "Hapus",
  edit: "Edit",
  isiCatatan: "Isi Catatan",
  petunjuk: "Petunjuk",
  penerima: "Penerima",
  tambahPenerima: "Tambah Penerima",
  masukkanNIKpenerima: "Masukkan NIK penerima",
  masukkanCatatan: "Masukkan catatan...",
  pilihPetunjuk: "Pilih petunjuk",
  cariPetunjuk: "Cari petunjuk...",
  pilihSifat: "Pilih sifat",
  pilihUrgensi: "Pilih urgensi",
  cariPenerima: "Cari penerima...",
  detailSurat: "Detail Surat",
  lihatPreview: "Lihat File",
  petunjukID: "Petunjuk ID",
  informasiDisposisi: "Informasi Disposisi",
  statusFile: "Status File",
  dibuatOleh: "Dibuat Oleh",
  versi: "Versi",
  hapusSurat: "Hapus Surat",
  hapusSuratMessage: "Apakah Anda yakin ingin menghapus surat ini?",
  editSurat: "Edit Surat",
  tidakAdaDataSuratMasuk: "Tidak ada data surat masuk",
  tteInbox: "TTE Inbox",
  tteOutbox: "TTE Outbox",
  createTTE: "Request TTE",
  nikPenerima: "NIK Penerima",
  jenisTTE: "Jenis TTE",
  masukkanNikPenerima: "Masukkan NIK penerima",
  pilihJenisTTE: "Pilih jenis TTE",
  paraf: "PARAF",
  tte: "TTE",
  buat: "Buat",
  hapusPenerima: "Hapus Penerima",
  minimalSatuPenerima: "Minimal harus ada satu penerima",
  inbox: "Inbox TTE",
  progress: "Progress",
  signSurat: "Sign Surat",
  rejectTTE: "Reject TTE",
  rejectTTEMessage: "Apakah Anda yakin ingin menolak TTE ini?",
  reject: "Reject",
  rejected: "Rejected",
  searchUserPlaceholder: "Cari nama, NIP, atau NIK...",
  signed: "Signed",
  izin: "Izin",
  buatIzin: "Buat Izin",
  riwayatIzin: "Riwayat Izin",
  kategoriIzin: "Kategori Izin",
  tanggalAwal: "Tanggal Awal",
  tanggalAkhir: "Tanggal Akhir",
  alasan: "Alasan",
  lampiran: "Lampiran",
  namaLampiran: "Nama Lampiran",
  fileLampiranDescription: "File lampiran wajib diisi (format PDF)",
  pilihKategoriIzin: "Pilih kategori izin",
  masukkanAlasan: "Masukkan alasan...",
  izinBerhasilDibuat: "Izin berhasil dibuat",
  gagalMembuatIzin: "Gagal membuat izin",
  tidakAdaDataIzin: "Tidak ada data izin",
  dinasLuar: "Dinas Luar",
  cutiTahunan: "Cuti Tahunan",
  cutiBesar: "Cuti Besar",
  cutiSakit: "Cuti Sakit",
  cutiMelahirkan: "Cuti Melahirkan",
  cutiAlasanPenting: "Cuti Alasan Penting",
  cutiLuarTanggunganNegara: "Cuti Luar Tanggungan Negara",
  izinTidakMasuk: "Izin Tidak Masuk",
  status: "Status",
  tanggal: "Tanggal",
  namaSurat: "Nama Surat",
};
