export const TEXT = {
  title: "Kementerian Haji dan Umrah",
  welcome: "Selamat Datang",
  welcomeDescription: "di Kementerian Haji dan Umrah App",
  reminderDescription: "Jangan lupa catat kehadiranmu hari ini.",
  clockIn: "Absen Masuk",
  clockOut: "Absen Keluar",
  lainnya: "Lainnya",
  presensi: "Presensi",
  kepegawaian: "Kepegawaian",
  persuratan: "Persuratan",
  sop: "SOP",
  laporan: "Laporan",
  semuaMenu: "Menu",
  laporanKehadiran: "Laporan Kehadiran",
  jadwalKerja: "Jadwal Kerja",
  stafKhusus: "Staf Khusus",
  stafKhususDescription: "08:00 - 17:00",
  persenPemotongan: "Persentase Pemotongan",
  infoKehadiran: "Klik tombol di atas untuk mencatat kehadiran Anda",
  riwayatKehadiran: "Riwayat Kehadiran",
  lihatSemua: "Lihat Semua",
  belumAdaDataKehadiranHariIni: "Belum ada data kehadiran hari ini",
  apakahAndaYakinInginMelakukanAbsen:
    "Apakah Anda yakin ingin melakukan absen?",
  yaAbsenMasuk: "Ya, Absen Masuk",
  yaAbsenKeluar: "Ya, Absen Keluar",
  batal: "Batal",
  konfirmasiAbsenMasuk: "Konfirmasi Absen Masuk",
  konfirmasiAbsenKeluar: "Konfirmasi Absen Keluar",
  harapIzinkanAksesLokasiUntukMelakukanAbsen:
    "Harap izinkan akses lokasi untuk melakukan absen",
  peringatan: "Peringatan",
  terjadiKesalahan: "Terjadi kesalahan, silahkan coba lagi",
  sukses: "Sukses",
  absenBerhasil: "Absen berhasil",
  absenMasukBerhasil: "Absen masuk berhasil",
  absenKeluarBerhasil: "Absen keluar berhasil",
  loginSSO: "Login SSO",
  keluarDariAkun: "Keluar dari akun",
  ya: "Ya",
  tidak: "Tidak",
  apakahAndaYakinInginKeluarDariAkun:
    "Apakah Anda yakin ingin keluar dari akun?",
  atasanLangsung: "Atasan Langsung",
  divisi: "Divisi",
  infoAkun: "Informasi Akun",
  pengaturan: "Pengaturan",
  infoPersonal: "Info Personal",
  infoKepegawaian: "Info Kepegawaian",
  infoLainnya: "Info Lainnya",
  ubahKataSandi: "Ubah Kata Sandi",
  pengingatPresensi: "Pengingat Presensi",
  bahasa: "Bahasa",
  pemotongan: "Pemotongan",
  memuatData: "Memuat data...",
  cobaLagi: "Coba Lagi",
  tidakAdaDataKehadiranUntukBulanIni:
    "Tidak ada data kehadiran untuk bulan ini",
};
